### ISSUE TITLE
Encountering a white screen when navigating with latest alpha

### ISSUE THREAD

**Issue by jamonholmgren** [kmagiera/react-native-screens#208]
Related issue: https://github.com/infinitered/ignite-bowser/issues/285

Steps to reproduce:

1. Run these commands:

```
npm i -g ignite-cli
ignite new MyApp -b bowser --no-detox
cd MyApp
react-native run-ios
```

2. Run it
3. Click the "Continue" button and observe:

<img src="https://user-images.githubusercontent.com/1479215/67913287-c488e100-fb49-11e9-8363-8466961392cd.png" width="200" />

If I remove the `enableScreens()` in the `app.tsx`, it no longer exhibits this behavior. Reloading the second screen also fixes the issue temporarily until I click back, after which it turns white on the home screen.

Any idea what's going on here?

**Comment by bwoodlt** [comment]
Having the same issue, any thoughts? `react-native:0.61.2` and `react-native-screens: 2.0.0-alpha.6`

**Comment by AfrazHussain** [comment]
Could be related to https://github.com/kmagiera/react-native-screens/issues/187? Are your screens nested in a stack inside a tab navigator?

**Comment by makarkotlov** [comment]
Same here. My screens are in stackNavigator inside of switchNavigator. I encounter white screens and  strange glitching when navigating between stacks

**Comment by jamonholmgren** [comment]
I think being nested in another navigator was the problem -- it appears to work well after this PR:

https://github.com/infinitered/ignite-bowser/pull/289

**Comment by limaAniceto** [comment]
Just to share my experience, in case it helps to pinpoint the issue.

This issue also happens if you have the following structure:
```createAppContainer(AppNavigator)```
```
const AppNavigator = createSwitchNavigator({
        Auth: {
            screen: AuthStack
        },
        App: {
            screen: TabNavigator
        })
```
```
const TabNavigator = createStackNavigator({
   myTab: {
            screen: createBottomTabNavigator(
                {
                    Home: HomeStack,
                    Profile: ProfileStack,
                }
})
```
```
const HomeStack = createStackNavigator(
    {
        home: {
            screen: HomeScreen,
            navigationOptions: {
                headerTitle: 'Home'
            }
        },
        Other: OtherScreen
   });
```
If you are on the `HomeScreen` and click on a button to navigate to `OtherScreen` you get the blank screen. If you just remove `enableScreens`, it works

**Comment by makarkotlov** [comment]
It seems to be fixed in the latest alpha 8 version. I don't have any lags after update

**Comment by AfrazHussain** [comment]
This is still definitely not fixed. I've tried fixing this on my fork, but to no avail.

P.S. I am using alpha version 4 in my production build. Version 8 even with the fix in this commit https://github.com/infinitered/ignite-bowser/pull/289/files doesn't work properly (tested only on iOS physical device). There is still spacing at the bottom of the screen.

**Comment by bwoodlt** [comment]
Having issue with this still. Any thoughts?

**Comment by sofiageo** [comment]
> Having issue with this still. Any thoughts?

Have you tried the latest alpha version? I had a similar issue that was fixed by upgrading from alpha 8 to alpha 11. I'm not sure why but my issue is gone both on Android and iOS.

**Comment by bjjeong** [comment]
Still getting this issue on alpha 11. Have been having to use alpha-4 as it's the last version that doesn't have this problem. I'm on `react-native@0.61.3`

![RNS](https://media.giphy.com/media/Kc8MWmF544iV2EctDv/giphy.gif)

**Comment by makarkotlov** [comment]
I'm on the last `alpha.11`. The lib crashes my app when I try to navigate to other stackNavigator inside of switchNavigator

**Comment by nphivu414** [comment]
I'm on alpha 15 now and this blank issue is still there on Android.  iOS works much better and rarely have this problem.

**Comment by tboerc** [comment]
I can say that @limaAniceto issue still happening only on Android, and I'm on alpha 16. If I use "useScreens()" method, it works normal, the problem is with "enableScreens()"

**Comment by dcosmin2003** [comment]
Hello, I'm using alpha 17 and RN 0.61.5 and still have this issue on iOS

**Comment by mistikk** [comment]
alpha 18 has same issue

**Comment by dcosmin2003** [comment]
I've downgraded to react-native-screens@^1.0.0-alpha.23 as the documentation is saying and removed the enableScreens, and now it looks fine on my side.

https://reactnavigation.org/docs/en/getting-started.html

**Comment by clamiax** [comment]
Issue is still there on Android with alpha.22.

**Comment by osdnk** [comment]
Can you open a new issue with some repro?

**Comment by clamiax** [comment]
@osdnk Sure, see #270

**Comment by Legi0n1138** [comment]
Experiencing this issue, at least on android.
```
"react-native-screens": "^2.0.0-alpha.15",
"react-native": "^0.61.5",
"react-navigation": "4.2.2",
"react-navigation-drawer": "1.4.0",
"react-navigation-stack": "1.7.3",
"react-navigation-tabs": "1.2.0",
```
Any known solutions?

**Comment by kmagiera** [comment]
@Legi0n1138 Please try react-native-screens@2.1.0 and report back if that did not solve the problem

**Comment by Legi0n1138** [comment]
@kmagiera `react-native-screens@2.1.0` solved the issue. Thanks!

**Comment by clems36** [comment]
I'm still experiencing this issue with  `"react-native-screens": "~2.9.0",` both on iOS and android.
`useScreens` gives the same result.
