### ISSUE TITLE
Screens are blank for a few frames when navigating to them

### ISSUE THREAD

**Issue by dereknelson** [kmagiera/react-native-screens#35]
Not sure if this is expected behavior or it's something to do with my configuration, but here's a [video slowed down to 25% speed](https://youtu.be/zOrCLWgzZbA)

My navigator setup: 
```
StackNavigator: {
    DrawerNavigator: {
        BottomTabNavigator: {
            StackNavigator: {
                Screen
            }
            StackNavigator: {
                Screen
            }
            ...SimilarStackNavigators
        }
    }
}
```

Happy to answer any other questions about my implementation. My app works significantly smoother now, very excited about this project.

**Comment by brentvatne** [comment]
can you provide an example that reproduces this?

**Comment by dereknelson** [comment]
@brentvatne hey have been pretty swamped but will be getting to reproducing as soon as I can. It does happen in both development and production.

**Comment by dereknelson** [comment]
@kmagiera forgot to update with this info - I've upgraded to Expo SDK 31 and there is no gray flash anymore. React-Navigation version is the same.

**Comment by kmagiera** [comment]
FYI we have found one more instance of this issue that may have cause a flash with stack navigator on Android. It's been addressed in #50 and also in react-navigation repo here https://github.com/react-navigation/react-navigation-stack/pull/73

Both react-nav changes and screens update will be released soon

**Comment by K-Leon** [comment]
I'm seeing this behaviour with react native router flux on android - it is using 2.x branch of react navigation as base.

I'm using latest screens and latest 2.x of react navigation - still seeing this flicker. Even if i backport the listed PR, removing opacity completly or switching to ios transitions. It is also not the root view that shines through - i'm wondering if there is any idea or fix that could help

**Comment by kmagiera** [comment]
Hey @K-Leon – unfortunately I have no idea how router flux is using react navigation under the hood but as far as I remember the change that fixed it in react navigation has been merged to 3.X not 2.X (might be wrong tho).

What helped me debug this in the past was to try record transision using screen recording and then playing in slow motion (managed to notice it was actually the transparency that's changed). If you have time to prepare such video and post it here in slow motion that might help.

I'm actually going to close this issue as it has been addressed a while ago. Can you please open a new one to hold the discussion about router flux?
